### ISSUE TITLE
There was an error loading the preference bundle for...

### ISSUE THREAD

**Issue by cfHxqA** [FouadRaheb/Watusi-for-WhatsApp#10]
Electra Version 1.0.2, latest Watusi 2 Version is installed, already removed and installed again. No changes.

Current ios: 11.1.2, iphone 8.

**Comment by FouadRaheb** [comment]
Try updating PreferenceLoader from rpetrich's repo (rpetri.ch/repo).

**Comment by FouadRaheb** [comment]
And you don't even need to access the preference bundle anyway, all Watusi settings are only available inside WhatsApp.

**Comment by cfHxqA** [comment]
PreferenceLoader already updated, multiple times. Im tried to install WhatsApp sideloading (not starting). The preference bundle is already required by installing Watusi 2 / Tools.

**Comment by FouadRaheb** [comment]
Sideloading has nothing to do here. Just try to update everything from rpetrich's repo and if that doesn't work you have to wait for rpetrich's updates. Please send me an email about any other issues instead of posting here.
