### ISSUE TITLE
pass code machine broke

### ISSUE THREAD

**Issue by StriK3FoRC3** [FouadRaheb/Watusi-for-WhatsApp#11]
the pass code is not working on ipad (luckly I enabled touch I'd, or I can't use the app anymore)
and can you add a feature were you can save all watusi settings( because It takes so long to get everything set again, when you install the app new)

thanks for your great work 👍 🥇 :)

![dc2d0a6f-fb20-45a4-8474-e8216491b0bc](https://user-images.githubusercontent.com/33492799/36819666-a21ac262-1cea-11e8-90d0-47bdcfca2489.png)

**Comment by FouadRaheb** [comment]
I'll check it out. Next time you have any issue please send me an email instead.
