### ISSUE TITLE
how to support icloud ?

### ISSUE THREAD

**Issue by Q8hma** [FouadRaheb/Watusi-for-WhatsApp#12]
Hello
i have dev account how can i add icloud and Push Notifications 
thnx

**Comment by n0o0n** [comment]
Gents,

My tow same problem I can’t gat WhatsApp Notifications!!!
How can we fix it ? Please

**Comment by FouadRaheb** [comment]
Signing the app is not related to Watusi tweak. 
Next time you have any issue please send me an email.
