### ISSUE TITLE
Whatsapp Watusi Crashing

### ISSUE THREAD

**Issue by xtptbx** [FouadRaheb/Watusi-for-WhatsApp#4]
Hello Fouad Raheb,

First of all thank you very much for offering this tweak via a Sideloaded version of Whatsapp. Makes alot of difference for us Non-JB folks.

Alright, the issue I am facing is with the latest version of Currently Available Whatsapp (2.17.71) Watusi (1.0.26) - This version is provided by AppDB.
I have even tested your version Whatsapp (2.17.70) Watusi (1.0.26).

Whenever I click on the Contact Information (the top bar inside a chat with someone for more information), it crashes. Also, I cannot enter the "Other Addons" section under Watusi Preferences.

I think this issue has been fixed on your updated tweak 1.0.27. I hope your release a sideloaded version as well (tested this on my Jailbroken i6s+.
The sideloaded version 2.17.61 works fine with no crashes.

Kindly, please fix these issues. Love your work.

Sincerely,
x The Power That Be x

**Comment by alihafizali6** [comment]
Sossoo

**Comment by FouadRaheb** [comment]
Do you still have the issue of crashing when opening Contact Information?

**Comment by ahsanrafiqch** [comment]
Hi,

Thanks for giving us freedom in using this app on non-jb devices. I am facing issue of inconsistent notifications and messages. I thought this might be the issue with my network but when I installed App Store version of WhatsApp, there was no lag and inconsistent notifications and messages. I get messages notifications in delay.

Please resolve this issue.
Thank You

**Comment by FouadRaheb** [comment]
It seems like you didn't read the note section in the tutorial :-) 

> The app will not receive Push Notifications and you won't be able to use iCloud features.
