### ISSUE TITLE
error installing Watusi using install.sh

### ISSUE THREAD

**Issue by SeMoOo** [FouadRaheb/Watusi-for-WhatsApp#6]
iPhone X iOS 11.1.2 using latest Electra and Whatsapp. I am unable to use the script to install Watusi, I get the below error in Terminal

> Download completed
Extracting files...
tar: Child died with signal 9
tar: Error is not recoverable: exiting now

Please help fixing it. I don't mind updating manually but having a script is beneficial.

**Comment by FouadRaheb** [comment]
What's the storage capacity of your device? It could be that your device system partition free space is not enough to extract the files.

**Comment by SeMoOo** [comment]
My device is 256 GB. I have plenty of free space

**Comment by FouadRaheb** [comment]
Which Electra version are you using?

**Comment by SeMoOo** [comment]
latest, B10.

**Comment by FouadRaheb** [comment]
Well I have no idea whats going on, did you try rebooting your device and running the command again?

**Comment by SeMoOo** [comment]
I did try it but i will do it again.

**Comment by SeMoOo** [comment]
still showing the same error.

**Comment by FouadRaheb** [comment]
It seems like Electra will include a Cydia build in the next updates which will fix all these issues.
You can also try installing it manually.
