### ISSUE TITLE
Relaunch/ Okay is not working - Electra

### ISSUE THREAD

**Issue by thaufeekrockz** [FouadRaheb/Watusi-for-WhatsApp#7]
Hi Fouad,

Thank you so much for your great works that helps Jb community much . i found a issue with relaunch option that is not relaunching after changing the theme and even Okay is not working that disable the options. 

Thanks and Regards 
Thaufeek Mohamed

**Comment by FouadRaheb** [comment]
Its because I did not include SpringBoard hooks on Electra so its not possible to relaunch WhatsApp.
