### ISSUE TITLE
grabar llamadas de whassap

### ISSUE THREAD

**Issue by claudioraice** [FouadRaheb/Watusi-for-WhatsApp#8]
estimados no se porque se quito pero se podria volvver a agregar la opcion de grabar las llmas. muy importante para mi por trabajo gracias.

**Comment by FouadRaheb** [comment]
According to Google translate, you are asking for call recording feature. 
WhatsApp removed their built-in call recorder which was used by Watusi to record the calls and I'm not planning to write my own call recorder at the moment.
