### ISSUE TITLE
New Install Location of Electra Jailbreak

### ISSUE THREAD

**Issue by aayushjain2019** [FouadRaheb/Watusi-for-WhatsApp#9]
There is no more bootstrap folder after jailbreaking with Electra 1.0.2

Hence, none of the existing methods work.

It needs to be updated.

**Comment by cfHxqA** [comment]
I got the same issue. Nothings options to see in WhatsApp application.

**Comment by FouadRaheb** [comment]
Install it from Cydia and do this workaround for now https://twitter.com/FouadRaheb/status/968428587144695808

**Comment by aayushjain2019** [comment]
Watusi on Cydia shows in the changelog that it works on ios 7,8,9 and 10.

When i installed it from Cydia, nothing happens. There is no Watusi option
in Whatsapp.


Plus, I am so glad and fortunate to talk to you sir. One of the primary
reasons I own and jailbreak iphones since years is because of your tweak.
Cheers!

**Comment by FouadRaheb** [comment]
Just after you install it from Cydia, follow the instructions I mentioned in the tweet and you should be able to fix it on Electra Jailbreak. I'm working on an update that should be submitted today.

You can always email with any issues/suggestions you have! Glad you like the tweak!

**Comment by cfHxqA** [comment]
Already tried solution from tweet without any effect. :( I wait for your update. It's better than experimenting. Thanks for your work!!
